name: Run Tests

on: [push]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://example.com/production
    steps:
    - name: Deploy
      run: echo deploy
