name: Run Tests

on: [push]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: productoin
      url: http://example.com/productino
    steps:
    - name: Deploy
      run: echp deploy
