name: Manual Trigger

on: 
  workflow_dispatch:
    inputs:
      numOctocats:
        description: 'Number of Octocats'
        required: false
        default: '1'
      octocatEyeColor:
        description: 'Eye color of the Octocats'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: run
        env:
          TAG: ${{ github.sha }}
        run: |
          echo Hello, world!
          echo GITHUB_SHA=$GITHUB_SHA
          ecoh TAG=$TAG
      
