name: 'project to label'

on: [issues]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: create issue
        if: github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: 'Project name1'
          column: 'start'
          repo-token: ${{ secrets.GH_TOKEN }}
      - name: project to label 1
        if: github.event.action == 'labeled' && github.event.label.name == 'Status::test1'
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: 'Project name1'
          column: 'Column name1'
          repo-token: ${{ secrets.GH_TOKEN }}
          #repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: project to label 2-1
        if: github.event.action == 'labeled' && contains(fromJSON('["Status::test2-1","Status::test2-2"]'), github.event.label.name)
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: 'Project name1'
          column: 'Column name2'
          repo-token: ${{ secrets.GH_TOKEN }}
